server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie
  error:
    path: /commonn/error
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never
    whitelabel:
      enabled: true

spring:
  datasource:
    url: